spring:
  application:
    name: blackjack-game

  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:mysql://localhost:3306/s05t01_db}
    username: ${SPRING_R2DBC_USERNAME:root}
    password: ${SPRING_R2DBC_PASSWORD:root}

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/s05t01_mongo}

  jackson:
    serialization:
      write-dates-as-timestamps: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG