spring:
  # MySQL Reactivo
  r2dbc:
    url: r2dbc:mysql://localhost:3306/s05t01_db
    username: root
    password: root

  # MongoDB Reactivo
  data:
    mongodb:
      uri: mongodb://localhost:27017/s05t01_mongo